# Generated by Django 5.0.6 on 2025-11-07 18:45

import cross_asistent.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encabezado', models.ImageField(blank=True, max_length=120, null=True, upload_to=cross_asistent.models.set_imgBlog_path)),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('autor', models.CharField(max_length=100)),
                ('creacion', models.DateField(auto_now_add=True)),
                ('actualizacion', models.DateField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=150, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=350, null=True)),
                ('redirigir', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, max_length=120, null=True, upload_to=cross_asistent.models.set_imgBanner_path)),
                ('expiracion', models.DateField(blank=True, null=True)),
                ('solo_imagen', models.BooleanField(default=False)),
                ('visible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('creacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Configuraciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_image', models.FileField(max_length=200, upload_to='settings/')),
                ('qr_button', models.BooleanField(default=True)),
                ('calendar_btnsYear', models.BooleanField(default=True)),
                ('copyright_year', models.CharField(default='2020', max_length=50)),
                ('utc_link', models.TextField()),
                ('redes_sociales', models.TextField(blank=True, null=True)),
                ('about_img_first', models.ImageField(max_length=200, upload_to=cross_asistent.models.set_conf_path)),
                ('about_img_second', models.ImageField(max_length=200, upload_to=cross_asistent.models.set_conf_path)),
                ('about_text_first', models.TextField()),
                ('about_text_second', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, max_length=120, null=True, upload_to=cross_asistent.models.set_imgs_path)),
                ('uuid', models.CharField(max_length=25)),
                ('usos', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=25)),
                ('nombre', models.CharField(max_length=200)),
                ('informacion', models.TextField()),
                ('color', models.CharField(max_length=50)),
                ('door_cords', models.CharField(max_length=150, null=True)),
                ('p1_polygons', models.CharField(blank=True, max_length=150, null=True)),
                ('p2_polygons', models.CharField(blank=True, max_length=150, null=True)),
                ('p3_polygons', models.CharField(blank=True, max_length=150, null=True)),
                ('p4_polygons', models.CharField(blank=True, max_length=150, null=True)),
                ('is_marker', models.BooleanField(default=False)),
                ('hide_name', models.BooleanField(default=True)),
                ('size_marker', models.CharField(default='0.05', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('informacion', models.TextField(blank=True, null=True)),
                ('redirigir', models.TextField(blank=True, null=True)),
                ('frecuencia', models.IntegerField(default=0)),
                ('documento', models.FileField(blank=True, max_length=120, null=True, upload_to=cross_asistent.models.set_pdfDB_path)),
                ('imagen', models.ImageField(blank=True, max_length=120, null=True, upload_to=cross_asistent.models.set_imgDB_path)),
                ('uuid', models.CharField(max_length=25)),
                ('evento_fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('evento_fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('evento_allDay', models.BooleanField(default=False)),
                ('evento_lugar', models.CharField(blank=True, default='Campus UTC', max_length=200, null=True)),
                ('evento_className', models.CharField(blank=True, default='event_detail', max_length=100, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cross_asistent.categorias')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, max_length=120, null=True, upload_to=cross_asistent.models.set_imgProfile_path)),
                ('tutorial', models.BooleanField(default=True)),
                ('blog_firma', models.CharField(blank=True, max_length=200, null=True)),
                ('password_update', models.DateField(blank=True, null=True)),
                ('user_token', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
